### ISSUE TITLE
Minor change in German localization

### ISSUE THREAD

**Issue by ersjoh** [cushion/invoice-translations#27]
Hi,
Thanks @te-online for your German localization!

Can we change the "_Freundlich berechnet für_" label to something more neutral, like "_Ausgestellt für_"? 

Let me know what you think!

Thanks,
Johannes

**Comment by te-online** [comment]
@ersjoh Thanks for your comment – yeah, I had a bit of a struggle to find a nice translation for the sticky english phrase and didn't want to go with something boring like „Empfänger“ (receipient).

„Ausgestellt für“ seems a lot better 😊  But still it doesn't feel completely right... (more like something you'd write in a passport). 
Anyways, because it's an improvement, I could add it later in a PR together with the new discount strings?

**Comment by ersjoh** [comment]
Thank you! I agree it's still not perfect, we might find a better translation later on. I'd appreciate if you add it with the other new strings! :)

**Comment by destroytoday** [comment]
Merged! Thanks!
